import { existsSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, test } from 'vitest';

// The default-only adapter CJS export shape is generated by the shared build template.
// Import it directly so the test does not depend on a pre-built dist artifact.
import createTsdownConfig from '@alova/scripts/src/build/tsdown.config.js';

// Mirrors `packages/alova/build.json` -> "fetch" bundle.
const fetchBundle = {
  packageName: 'alovaFetch',
  input: 'src/predefine/adapterFetch.ts',
  external: { '@alova/shared': null },
  output: './dist/adapter/fetch.{suffix}.{ext}'
};

describe('CJS interop footer for default-only adapter bundles', () => {
  // Typed loosely on purpose: the build template is plain JS and its `format` field is a
  // union type that cannot be indexed by a numeric literal under the strict project config.
  const configs = createTsdownConfig(fetchBundle, '3.5.1') as any[];
  const cjsConfig = configs.find(c => c.config.format[0] === 'cjs');
  const esmConfig = configs.find(c => c.config.format[0] === 'esm');
  const umdConfig = configs.find(c => c.config.format[0] === 'umd');
  const footer: string = cjsConfig?.config.footer ?? '';

  test('injects the non-breaking interop footer into the CJS (common) output', () => {
    expect(cjsConfig).toBeDefined();
    expect(footer).toContain('module.exports.default = module.exports');
    expect(footer).toContain("Object.defineProperty(module.exports, '__esModule'");
  });

  test('does not overwrite the callable `module.exports` (so `require("alova/fetch")()` still works)', () => {
    // The footer must only ADD `.default` / `__esModule`, never reassign `module.exports = ...`.
    expect(footer).not.toMatch(/module\.exports = [^.]/);
  });

  test('does not inject the interop footer into non-CJS (esm) outputs', () => {
    const esmFooter: string = esmConfig?.config.footer ?? '';
    expect(esmFooter).not.toContain('__esModule');
  });

  test('does not inject the interop footer into umd outputs (require interop is a commonjs concern)', () => {
    const umdFooter: string = umdConfig?.config.footer ?? '';
    expect(umdFooter).not.toContain('__esModule');
  });
});

describe('built dist/adapter/fetch.common.cjs runtime interop', () => {
  // Resolve relative to this file (ESM-safe) so it works regardless of the vitest cwd.
  const builtCjs = resolve(dirname(fileURLToPath(import.meta.url)), '../../dist/adapter/fetch.common.cjs');
  const require2 = createRequire(import.meta.url);

  test.skipIf(!existsSync(builtCjs))('is callable and exposes .default + __esModule', () => {
    const mod = require2(builtCjs);
    expect(typeof mod).toBe('function');
    expect(typeof mod.default).toBe('function');
    // .default must reference the same factory, otherwise `require("alova/fetch").default()` breaks.
    expect(mod.default).toBe(mod);
    expect(mod.__esModule).toBe(true);
    // Non-breaking: the module itself stays callable, so `require("alova/fetch")()` keeps working.
    const directHandler = mod({ customFetch: () => new Promise(() => {}) });
    expect(typeof directHandler).toBe('function');
  });

  test.skipIf(!existsSync(builtCjs))('returns a usable request adapter instance', () => {
    const adapterFetch = require2(builtCjs);
    const makeAdapter = adapterFetch.default ?? adapterFetch;
    // Inject a stub fetch so no real network request is made during the test.
    const handler = makeAdapter({ customFetch: () => new Promise(() => {}) });
    expect(typeof handler).toBe('function');
    const controls = handler({ url: 'http://localhost/', type: 'GET', data: undefined, headers: {} }, { config: {} });
    expect(typeof controls.response).toBe('function');
    expect(typeof controls.headers).toBe('function');
    expect(typeof controls.abort).toBe('function');
  });
});
