branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'
  - - '@semantic-release/exec'

    # 使用下一个版本号执行打包命令
    - prepareCmd: 'cross-env VERSION=${nextRelease.version} npm run build'
