export { key as getMethodKey } from '@alova/shared/function';
export { default as Method } from './Method';
export { createAlova } from './alova';
export * from './functions/manipulateCache';
export { default as updateState } from './functions/updateState';
export { default as globalConfig } from './globalConfig';
export { default as useFetcher } from './hooks/useFetcher';
export { default as useRequest } from './hooks/useRequest';
export { default as useWatcher } from './hooks/useWatcher';
export { promiseStatesHook } from './utils/helper';
