title: "\U0001F680 Feature Request:"
labels: ['feature-request']
body:
  - type: markdown
    attributes:
      value: |
        :wave: Hi, thank you so much for supporting alova, it's really important for us!

        **We aim to build alova into a common project for everyone, and encourage every developer to become a contributor to the alova community with an open and inclusive attitude. If you're interested, you can try to contribute by submitting a PR, it will let developers all over the world to use your code, please [see CONTRIBUTING](https://github.com/alovajs/alova/blob/main/CONTRIBUTING.md) for more details!**

        :warning: Please read the following before submitting a new feature request/proposal:
        - Confirm that it cannot be implemented through the existing APIs. Usually, we only add new features when the problem cannot be easily solved by the existing APIs, not just an alternative way of doing what can already be done
        - Confirm that it is in line with alova's goal, please [see the goal of alova](https://github.com/alovajs/alova/blob/main/CONTRIBUTING.md#goal-of-alova)
        - Make sure no duplicates are found in [Issues](https://github.com/alovajs/alova/issues) or [Discussion](https://github.com/alovajs/alova/discussions).

  - type: textarea
    id: description
    attributes:
      label: What problem does the new feature need to solve?
      description: Before committing, please make sure to read [alova's development direction](../../CONTRIBUTING.md#goal-of-alova).
    validations:
      required: true

  - type: textarea
    id: expectation
    attributes:
      label: How should the new features you expect looks like?
      description: You can provide a code design snippet of a new feature to express how the new feature you expect looks like in the new version.

  - type: dropdown
    id: importance
    attributes:
      label: How important is it to you?
      options:
        - Better to have
        - Can make it easier to develop
        - I'll give up alova without it
    validations:
      required: true
