name: Issue labeler for Chinese
on:
  issues:
    types: [ opened ]

permissions:
  contents: read

jobs:
  label-component:
    if: contains(github.event.issue.labels.*.name, 'lang:chinese')
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

      # only required for workflows in private repositories
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/02.bug_report_zh-CN.yml

      - name: Set labels based on framework field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: framework
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}